import { Metadata } from "next"
import Navigation from "../components/Navigation"

export const metadata: Metadata = {
  // meta data 수정, 추가 할 수 있음
  title: {
    template: "%s | My Website", // template으로 추가 가능
    default: "My Website"
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  )
}
